# Configuration file for the XrmNode Unit tests
nodewebapi:
 logging: verbose
 runIntegrationTests: true
 proxy:
  useproxy: false
  httpProxy: http://127.0.0.1:8888
  httpsProxy: http://127.0.0.1:8888
 server:
  host: https://dev1demos13.crm3.dynamics.com
  version: 9.1